global:
  threadmodel:
    fiber:
      - instance_name: fiber_instance

client:
  service:
    - name: mysql_server
      protocol: trpc
      timeout: 3000
      network: tcp
      conn_type: long
      is_conn_complex: true
      target: 127.0.0.1:3306
      selector_name: direct
      max_conn_num: 16
      idle_time: 40000

      mysql:
        user_name: "root"
        password: "abc123"
        dbname: "test"
        num_shard_group: 2
        thread_num: 6
        thread_bind_core: true
        enable: true


plugins:
  log:
    default:
      - name: default
        sinks:
          local_file:
            filename: trpc_fiber_client.log
