global:
  threadmodel:
    fiber:
      - instance_name: fiber_instance

client:
  service:
    - name: mysql_server
      protocol: trpc
      timeout: 1000
      network: tcp
      conn_type: long
      is_conn_complex: true
      target: 127.0.0.1:3306
      selector_name: test_selector

      mysql:
        user_name: "root"
        password: "abc123"
        dbname: "test"
        ip: "localhost"
        port: 3306
        enable: true
        connectpool:
          min_size: 100
          max_size: 200
          max_idle_time: 500
          timeout: 200

        
    
  filter:
    - promethues

plugins:
  log:
    default:
      - name: default
        min_level: 2 # 0-trace, 1-debug, 2-info, 3-warn, 4-error, 5-critical
        mode: 1 # 1-sync 2-async, 3-fast
        sinks:
          local_file:
            eol: true
            filename: mysql_fiber_client.log
