global:
  threadmodel:
    fiber:
      - instance_name: fiber_instance

server:
  app: Test
  server: HelloWorldServer
  admin_port: 8888
  admin_ip: 0.0.0.0
  registry_name: test_registry
  service:
    - name: trpc.test.helloworld.Greeter
      network: tcp
      ip: 0.0.0.0
      port: 10001
      protocol: trpc
      max_conn_num: 10000
      queue_timeout: 5000
      idle_time: 60000
      max_packet_size: 10000000
  filter:
    - promethues

client:
  service:
    - name: trpc.test.helloworld.Greeter
      protocol: trpc
      timeout: 1000
      network: tcp
      conn_type: long
      is_conn_complex: true
      target: trpc.test.helloworld.Greeter
      selector_name: test_selector

      mysql:
        user_name: "root"
        password: "abc123"
        dbname: "test"
        ip: "localhost"
        port: 3306
        enable: true
        connectpool:
          min_size: 100
          max_size: 200
          max_idle_time: 500
          timeout: 200

        
    
  filter:
    - promethues

plugins:
  registry:
    test_registry:
  selector:
    test_selector:
