global:
  threadmodel:
    default:
      - instance_name: default_instance
        io_handle_type: separate
        io_thread_num: 2
        handle_thread_num: 2

client:
  service:
    - name: mysql_server
      protocol: trpc
      timeout: 3000
      network: tcp
      conn_type: long
      is_conn_complex: true
      target: 127.0.0.1:3306
      selector_name: direct

      mysql:
        user_name: "root"
        password: "abc123"
        dbname: "test"
        enable: true
        max_size: 8


plugins:
  log:
    default:
      - name: default
        sinks:
          local_file:
            filename: trpc_fiber_client.log
